name: Running tests and linters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
  test:
    needs: lint
    strategy:
      matrix:
        go: [1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Tests
        run: |
          go test -v ./...
