name: Running tests and linters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --verbose
  test:
    needs: lint
    strategy:
      matrix:
        go: ["1.21", "1.22", "1.23", "1.24", "1.25", "1.26"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: Run Tests
        run: go test -v ./...
